spring:
  datasource:
    url: jdbc:mysql://localhost:3307/devblog?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    cors:
      allowed-origins: "http://localhost:5173"  # 프론트엔드 주소 추가
      allowed-methods: GET, POST, PUT, DELETE, PATCH  # 필요한 HTTP 메소드 추가
      allowed-headers: "*"  # 모든 헤더 허용
      allow-credentials: true  # 쿠키 전송 허용

server:
  port: 8080
